# Generated by Django 2.2 on 2020-03-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='granted_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
