# Generated by Django 2.2 on 2020-03-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0003_auto_20200312_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
